### PR TITLE
Add and export hex_core:version/0

### PR DESCRIPTION
**Pull request by starbelly**
- Added version/0 to hex_core which is intended to be used for
  backwards compat work-arounds by other apps and libs.

### CODE REVIEW

**Comment by wojtekmach** [comment]
Thank you!

**Comment by wojtekmach** [comment]
@starbelly since Rebar will now vendor hex_core, do you think we should still have `hex_core:version/0`?

I'm not opposed to having this function, but if primary beneficiary of it will no longer need it, I'm just wondering. Besides, I think users could do: `application.get_key(hex_core, vsn)` (but only when it's added as a dep, not when vendored!)

What do you think?

cc @ericmj

**Comment by starbelly** [comment]
@wojtekmach We'll probably still need to deal with backwards compat problems in rebar3_hex. The `application.get_key(hex_core, vsn)` call returns undefined for me (`application:get_key(hex_core, vsn`). But yeah, if we can get that working that would be fine 😄

**Comment by wojtekmach** [comment]
@starbelly oh, the application is probably not loaded. What happens when you do the following?

```erlang
application:load(hex_core), application:get_key(hex_core, vsn).
```

if that works, the proper fix is probably to add it to application list in `.app.src`.

**Comment by starbelly** [comment]
Derp. Yeah, working now. Safe to remove hex_core:version/0.

**Pull request merged**
