### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by ericmj** [comment]
The `src/hex_erl_tar.hrl` file is vendored so we don't want to make any changes to it.

**Comment by kianmeng** [comment]
> src/hex_erl_tar.hrl

@ericmj Reverted. Do you know where is the original source from?

**Comment by ericmj** [comment]
> Do you know where is the original source from?

https://github.com/erlang/otp/blob/master/lib/stdlib/src/erl_tar.erl

**Comment by ericmj** [comment]
Thank you!

**Pull request merged**
