### PR TITLE
Include CHANGELOG.md in the Hex package

### LINKED ISSUE #98: Include CHANGELOG.md in the Hex package
So that it shows up e.g. here: https://diff.hex.pm/diff/hex_core/0.6.9..0.6.10

### PR DESCRIPTION
**Pull request by starbelly**
- closes #98 
- use include_files app option to add CHANGELOG.md to hex_core package release

### CODE REVIEW

**Comment by ericmj** [comment]
I can't find docs for `include_files`: https://rebar3.org/docs/package_management/publishing-packages/. Is it additive or does it replace all files included by default?

Mix includes the changelog by default, maybe rebar3 should do the same? https://github.com/hexpm/hex/blob/main/lib/mix/tasks/hex.build.ex#L74-L75

**Comment by starbelly** [comment]
@ericmj it's only [additive](https://github.com/tsloughter/rebar3_hex/blob/609146be594317787c656937a872616b3ae72ca8/src/rebar3_hex_publish.erl#L301), documentation needs some ❤️

**Comment by starbelly** [comment]
Yeah, @ericmj thinking about this more... I agree, I think it makes make sense just to add `CHANGELOG.md` to default files in rebar3_hex. Let me open a PR on rebar3_hex for that and if Tristan and/or Fred agree we'll go with that and close this.

**Comment by starbelly** [comment]
https://github.com/tsloughter/rebar3_hex/pull/188

**Review by ericmj — APPROVED** [review]
Thanks! This looks good. I think we can merge this even if rebar3 will add it by default in the future.

**Comment by wojtekmach** [comment]
Thanks!

**Pull request merged**
