### PR TITLE
Create hex_repo functions

### PR DESCRIPTION
**Pull request by cgerling**
This PR creates the three functions mentioned in https://github.com/hexpm/hex/issues/738, those functions are required in order to complete one of the items in that issue.

### CODE REVIEW

**Review by wojtekmach — APPROVED** [review]
LGTM except I don’t think we should have get_installs as it is specific to hex.pm, ie other repositories would not have it. I think public key and docs ones make sense though.

**Comment by cgerling** [comment]
In this case, should we keep the existing implementation of `get_installs/0` in `hex` using `HTTP` directly?

**Comment by cgerling** [comment]
I've removed the `get_installs/1` from the PR

**Review by ericmj — APPROVED** [review]

**Comment by wojtekmach** [comment]
Thank you!

**Pull request merged**
